TPL_ITEM.HCR = ItemTpl()
    :name("合成结果")
    :icon("AB1")
    :description("合成的成品")
TPL_ITEM.HC1 = ItemTpl()
    :name("合成零件1")
    :icon("AB2")
    :description("合成的零件之一")
TPL_ITEM.HC2 = ItemTpl()
    :name("合成零件2")
    :icon("AB3")
    :description("合成的零件之一")
TPL_ITEM.HC3 = ItemTpl()
    :name("合成零件3")
    :icon("AB4")
    :description("合成的零件之一")
TPL_ITEM.HC4 = ItemTpl()
    :name("合成零件4")
    :icon("AB5")
    :description("合成的零件之一")