-- 漂浮字符
mtg.char("default", "0", "xlik_word_0", 1.9)
mtg.char("default", "1", "xlik_word_1", 1.8)
mtg.char("default", "2", "xlik_word_2", 1.8)
mtg.char("default", "3", "xlik_word_3", 1.8)
mtg.char("default", "4", "xlik_word_4", 1.8)
mtg.char("default", "5", "xlik_word_5", 1.8)
mtg.char("default", "6", "xlik_word_6", 1.8)
mtg.char("default", "7", "xlik_word_7", 1.8)
mtg.char("default", "8", "xlik_word_8", 1.8)
mtg.char("default", "9", "xlik_word_9", 1.8)
mtg.char("default", "+", "xlik_word_+", 1.7)
mtg.char("default", "-", "xlik_word_-", 1.7)
mtg.char("default", "C", "xlik_word_crit", 2.5)