--assets_image("border/square_orangeRed/*") -- 序列模式
assets_image("border/square_orangeRed/01")
assets_image("border/square_orangeRed/02")
assets_image("border/square_orangeRed/03")
assets_image("border/square_orangeRed/04")
assets_image("border/square_orangeRed/05")
assets_image("border/square_orangeRed/06")
assets_image("border/square_orangeRed/07")
assets_image("border/square_orangeRed/08")
assets_image("border/square_orangeRed/09")
assets_image("border/square_orangeRed/10")
assets_image("border/square_orangeRed/11")