assets_model("eff/Crit", "lik_crit")
assets_model("eff/CritAbility", "lik_crit_ability")

assets_model("ttg/Avoid", "lik_ttg_avoid")
assets_model("ttg/ImmuneDamage", "lik_ttg_immune_damage")
assets_model("ttg/ImmuneEnchant", "lik_ttg_immune_enchant")
assets_model("ttg/ImmuneInvincible", "lik_ttg_immune_invincible")
assets_model("ttg/EnchantDark", "lik_ttg_e_dark")
assets_model("ttg/EnchantFire", "lik_ttg_e_fire")
assets_model("ttg/EnchantGrass", "lik_ttg_e_grass")
assets_model("ttg/EnchantIce", "lik_ttg_e_ice")
assets_model("ttg/EnchantLight", "lik_ttg_e_light")
assets_model("ttg/EnchantPoison", "lik_ttg_e_poison")
assets_model("ttg/EnchantRock", "lik_ttg_e_rock")
assets_model("ttg/EnchantThunder", "lik_ttg_e_thunder")
assets_model("ttg/EnchantWater", "lik_ttg_e_water")
assets_model("ttg/EnchantWind", "lik_ttg_e_wind")
assets_model("ttg/EnchantSteel", "lik_ttg_e_steel")
assets_model("ttg/CritAbilityOrange", "lik_ttg_crit")

assets_model("ttg/WordOrange+", "lik_word_+")
assets_model("ttg/WordOrange-", "lik_word_-")
assets_model("ttg/WordOrange0", "lik_word_0")
assets_model("ttg/WordOrange1", "lik_word_1")
assets_model("ttg/WordOrange2", "lik_word_2")
assets_model("ttg/WordOrange3", "lik_word_3")
assets_model("ttg/WordOrange4", "lik_word_4")
assets_model("ttg/WordOrange5", "lik_word_5")
assets_model("ttg/WordOrange6", "lik_word_6")
assets_model("ttg/WordOrange7", "lik_word_7")
assets_model("ttg/WordOrange8", "lik_word_8")
assets_model("ttg/WordOrange9", "lik_word_9")
assets_model("ttg/WordOrangeCrit3", "lik_word_crit")

assets_model("interface/BossAlert") -- 指示器[条]100*750
assets_model("interface/BossAlertRing") -- 指示器[圆]160
assets_model("interface/BossAlertSquare") -- 指示器[正方]160