assets_model("eff/Crit", "xlik_crit")
assets_model("eff/CritAbility", "xlik_crit_ability")

assets_model("ttg/Avoid", "xlik_ttg_avoid")
assets_model("ttg/ImmuneDamage", "xlik_ttg_immune_damage")
assets_model("ttg/ImmuneEnchant", "xlik_ttg_immune_enchant")
assets_model("ttg/ImmuneInvincible", "xlik_ttg_immune_invincible")
assets_model("ttg/EnchantDark", "xlik_ttg_e_dark")
assets_model("ttg/EnchantFire", "xlik_ttg_e_fire")
assets_model("ttg/EnchantGrass", "xlik_ttg_e_grass")
assets_model("ttg/EnchantIce", "xlik_ttg_e_ice")
assets_model("ttg/EnchantLight", "xlik_ttg_e_light")
assets_model("ttg/EnchantPoison", "xlik_ttg_e_poison")
assets_model("ttg/EnchantRock", "xlik_ttg_e_rock")
assets_model("ttg/EnchantThunder", "xlik_ttg_e_thunder")
assets_model("ttg/EnchantWater", "xlik_ttg_e_water")
assets_model("ttg/EnchantWind", "xlik_ttg_e_wind")
assets_model("ttg/EnchantSteel", "xlik_ttg_e_steel")
assets_model("ttg/CritAbilityOrange", "xlik_ttg_crit")

assets_model("ttg/WordOrange+", "xlik_word_+")
assets_model("ttg/WordOrange-", "xlik_word_-")
assets_model("ttg/WordOrange0", "xlik_word_0")
assets_model("ttg/WordOrange1", "xlik_word_1")
assets_model("ttg/WordOrange2", "xlik_word_2")
assets_model("ttg/WordOrange3", "xlik_word_3")
assets_model("ttg/WordOrange4", "xlik_word_4")
assets_model("ttg/WordOrange5", "xlik_word_5")
assets_model("ttg/WordOrange6", "xlik_word_6")
assets_model("ttg/WordOrange7", "xlik_word_7")
assets_model("ttg/WordOrange8", "xlik_word_8")
assets_model("ttg/WordOrange9", "xlik_word_9")
assets_model("ttg/WordOrangeCrit1", "xlik_word_crit")

assets_model("interface/BossAlert") -- 指示器[条]100*750
assets_model("interface/BossAlertRing") -- 指示器[圆]160
assets_model("interface/BossAlertSquare") -- 指示器[正方]160