TPL_UNIT.Assault0 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)

TPL_UNIT.Assault1 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)
    :flyHeight(200)

TPL_UNIT.Assault2 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)
    :stature(100)

TPL_UNIT.Assault3 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)
    :flyHeight(200)
    :stature(100)

TPL_UNIT.Assault4 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)
    :flyHeight(400)
    :stature(30)

TPL_UNIT.Assault5 = UnitTpl()
    :preNoAttack()
    :move(5)
    :model("Footman")
    :icon("unit\\Footman")
    :hp(999999)
    :flyHeight(400)
    :stature(30)
