--- 黑游
TPL_UNIT.DarkRanger = UnitTpl("DarkRanger")
    :model("BansheeRanger")
    :scale(1.2)
    :level(1)
    :reborn(2)
    :hp(1000)
    :mp(100)
    :move(522)
    :attack(1)
    :attackSpaceBase(1.5)
    :attackRange(1000)