--- 火焰巨魔
TPL_UNIT.HeroFlameLord = UnitTpl("HeroFireLord")
    :preAbility({ TPL_ABILITY.AB1, TPL_ABILITY.AB2, TPL_ABILITY.AB3, TPL_ABILITY.AB4, TPL_ABILITY.King })
    :preItem({ TPL_ITEM.IT1, TPL_ITEM.IT2, TPL_ITEM.IT1, TPL_ITEM.IT2, TPL_ITEM.IT4 })
    :name("火焰巨魔")
    :model("HeroFlameLord")
    :scale(1.2)
    :icon("unit\\HeroAvatarOfFlame")
    :level(1)
    :reborn(2)
    :hp(1000)
    :hpRegen(150)
    :mp(100)
    :mpRegen(10)
    :move(522)
    :assault(Assault({ mode = "missile", model = "FaerieDragonMissile", homing = true, height = 200, speed = 1200 }))
    :attack(300)
    :attackSpaceBase(2)
    :attackRange(800)
    :attackSpeed(100)
    :crit(10)
    :odds("crit", 10)
    :hpSuckAttack("+=10")
    :mpSuckAttack("+=10")